# Generated by Django 4.2 on 2023-07-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="songprops",
            name="artist",
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
