# Generated by Django 4.2 on 2023-07-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0002_songprops_artist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("danceability", models.IntegerField()),
                ("energy", models.IntegerField()),
                ("mode", models.IntegerField()),
                ("valence", models.IntegerField()),
                ("tempo", models.IntegerField()),
                ("uri", models.TextField()),
                ("key", models.IntegerField()),
                ("popularity", models.IntegerField()),
                ("genre", models.CharField(max_length=255)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="Anther.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("owner", models.CharField(max_length=100)),
                ("number_of_likes", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "songs",
                    models.ManyToManyField(related_name="playlists", to="Anther.song"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artist",
            name="playlists_featured_on",
            field=models.ManyToManyField(
                related_name="featured_artists", to="Anther.playlist"
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="tracks",
            field=models.ManyToManyField(
                related_name="featured_artists", to="Anther.song"
            ),
        ),
    ]
