# Generated by Django 4.2 on 2023-07-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0003_artist_song_playlist_artist_playlists_featured_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song", name="danceability", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="song", name="energy", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="song", name="tempo", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="song", name="valence", field=models.FloatField(),
        ),
    ]
