# Generated by Django 4.2 on 2023-07-24 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0004_alter_song_danceability_alter_song_energy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="cover_image",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playlist", name="owner", field=models.JSONField(),
        ),
    ]
