# Generated by Django 4.2 on 2023-07-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0005_playlist_cover_image_alter_playlist_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist", old_name="number_of_likes", new_name="follow_count",
        ),
    ]
