# Generated by Django 4.2 on 2023-07-24 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0006_rename_number_of_likes_playlist_follow_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="uri",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
