# Generated by Django 4.2 on 2023-07-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0008_songrelationship_delete_songprops"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songrelationship",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
