# Generated by Django 4.2 on 2023-07-28 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0009_alter_songrelationship_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="uri",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
