# Generated by Django 4.2 on 2023-07-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0010_artist_uri"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
    ]
