# Generated by Django 4.2 on 2023-07-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0011_mailinglist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
