# Generated by Django 4.2.3 on 2024-01-18 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Anther", "0013_artist_created_at_artist_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TS", "T-Shirts"),
                            ("HT", "Hats"),
                            ("HD", "Hoodie"),
                            ("PT", "Posters"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=6),
                ),
                ("inventory", models.IntegerField(default=0)),
                ("sold", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FB", "Facebook"),
                            ("IG", "Instagram"),
                            ("TW", "Twitter"),
                            ("SP", "Spotify"),
                            ("YT", "YouTube"),
                            ("LV", "Real World"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongMetrics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("song_title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("spotify_uri", models.CharField(blank=True, max_length=200)),
                ("spotify_streams", models.IntegerField(default=0)),
                ("apple_music_streams", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("playlists", models.ManyToManyField(to="Anther.playlist")),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Anther.song"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneySpent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("spent_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneyReceived",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("source", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("received_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("receipt_image", models.ImageField(blank=True, upload_to="receipts")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CA", "Cash"),
                            ("BT", "Bank Transfer"),
                            ("PP", "PayPal"),
                            ("CC", "Credit Card"),
                        ],
                        default="CA",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "merch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Anther.merch"
                    ),
                ),
                (
                    "money_spent",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Anther.moneyspent",
                    ),
                ),
                (
                    "platforms",
                    models.ManyToManyField(
                        related_name="campaigns", to="Anther.platform"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistFollower",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_followers", models.IntegerField()),
                ("spotify_monthly_listeners", models.IntegerField()),
                ("ig_followers", models.IntegerField()),
                ("tiktok_followers", models.IntegerField()),
                ("youtube_subscribers", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Anther.artist"
                    ),
                ),
            ],
        ),
    ]
