# Generated by Django 4.2.3 on 2024-01-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anther", "0014_merch_platform_songmetrics_moneyspent_moneyreceived_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistfollower",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
